# Réglages personnels de makepkg. Le fichier système /etc/makepkg.conf reste
# aligné sur le paquet Arch afin de simplifier le traitement des .pacnew.
MAKEFLAGS="-j$(nproc)"
BUILDENV=(!distcc color ccache check !sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)
