complete -c arch-maintenance -s h -l help -d 'Afficher l’aide'
complete -c arch-maintenance -s y -l yes -d 'Tout exécuter automatiquement'
complete -c arch-maintenance -s d -l dry-run -d 'Simuler toutes les actions'
complete -c arch-maintenance -l check -d 'Audit en lecture seule'
complete -c arch-maintenance -s n -l no-update -d 'Ignorer les mises à jour'
complete -c arch-maintenance -l no-aur -d 'Ignorer les paquets AUR'
complete -c arch-maintenance -l no-zinit -d 'Ignorer Zinit et ses greffons'
complete -c arch-maintenance -s c -l no-cache-clean -d 'Conserver tous les caches'
complete -c arch-maintenance -s o -l no-orphans -d 'Conserver les paquets orphelins'
complete -c arch-maintenance -s j -l no-journal-clean -d 'Conserver les anciens journaux'
complete -c arch-maintenance -s b -l no-backup -d 'Ignorer la sauvegarde Pacman'
complete -c arch-maintenance -s B -l no-backup-config -d 'Ignorer la sauvegarde des configurations'
complete -c arch-maintenance -s f -l no-flatpak -d 'Ignorer Flatpak'
complete -c arch-maintenance -l mirrors -d 'Actualiser les miroirs avec Reflector'
complete -c arch-maintenance -s m -l no-mirrors -d 'Ne pas actualiser les miroirs'
complete -c arch-maintenance -s t -l no-trim -d 'Ne pas lancer le TRIM de secours'
complete -c arch-maintenance -l allow-on-battery -d 'Autoriser la maintenance sur batterie'
