general {
    gaps_in = 2
    gaps_out = 20
    border_size = 1
    col.active_border = rgb(1a1714)
    col.inactive_border = rgb(d1d1d1)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    rounding_power = 2
    active_opacity = 0.9
    inactive_opacity = 0.9

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 8
        passes = 3
        noise = 0.02
        contrast = 0.9
        brightness = 0.7
        vibrancy = 0.2
        new_optimizations = true
    }
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
