monitor = DP-2, 3840x2160@160, 0x0, auto
monitor = HDMI-A-1, 1920x1080@60, 3840x0, auto
workspace=1, monitor:DP-2, default:true, persistent:true 
workspace=2, monitor:HDMI-A-1, default:true, persistent:true 
